import type { ChokePoint, GeopoliticalEvent, WorldMonitorData } from "@/types";

const CHOKE_POINTS: ChokePoint[] = [
  {
    id: "taiwan-strait",
    name: "Taiwan Strait",
    lat: 24.5,
    lng: 120.0,
    type: "shipping",
    description: "One of the world's busiest shipping lanes. ~40% of global container traffic transits annually.",
    trafficVolume: "high",
  },
  {
    id: "bashi-channel",
    name: "Bashi Channel",
    lat: 21.0,
    lng: 121.0,
    type: "shipping",
    description: "Strategic passage between Taiwan and the Philippines connecting South China Sea to the Pacific.",
    trafficVolume: "high",
  },
  {
    id: "luzon-strait",
    name: "Luzon Strait",
    lat: 20.5,
    lng: 120.5,
    type: "shipping",
    description: "Critical maritime corridor between Taiwan and Luzon, key naval transit route.",
    trafficVolume: "medium",
  },
  {
    id: "miyako-strait",
    name: "Miyako Strait",
    lat: 24.5,
    lng: 125.5,
    type: "aviation",
    description: "Air defense identification corridor between Okinawa and Miyako-jima.",
    trafficVolume: "medium",
  },
  {
    id: "tsushima-strait",
    name: "Tsushima Strait",
    lat: 33.5,
    lng: 129.5,
    type: "shipping",
    description: "Major shipping route between Japan and Korea, indirectly linked to regional supply chains.",
    trafficVolume: "medium",
  },
  {
    id: "malacca-strait",
    name: "Strait of Malacca",
    lat: 2.5,
    lng: 101.0,
    type: "shipping",
    description: "World's second-busiest waterway, critical for Taiwan-bound energy and trade shipments.",
    trafficVolume: "high",
  },
  {
    id: "sunda-strait",
    name: "Sunda Strait",
    lat: -6.0,
    lng: 105.5,
    type: "shipping",
    description: "Alternative shipping route to Malacca, used during disruptions affecting Taiwan trade.",
    trafficVolume: "low",
  },
];

const GEOPOLITICAL_EVENTS: GeopoliticalEvent[] = [
  {
    id: "evt-1",
    lat: 24.5,
    lng: 120.0,
    title: "PLA Naval Drill in Taiwan Strait",
    description: "Multiple PLA Navy vessels transiting the Taiwan Strait in a coordinated exercise pattern.",
    eventType: "military",
    timestamp: Date.now() - 3600000 * 3,
    severity: "high",
    source: "OSINT Maritime Monitor",
  },
  {
    id: "evt-2",
    lat: 25.03,
    lng: 121.56,
    title: "Taipei Diplomatic Summit",
    description: "Bilateral trade delegation meetings with semiconductor industry leaders.",
    eventType: "diplomatic",
    timestamp: Date.now() - 3600000 * 6,
    severity: "medium",
    source: "Ministry of Foreign Affairs",
  },
  {
    id: "evt-3",
    lat: 24.8,
    lng: 120.99,
    title: "Hsinchu Science Park Expansion",
    description: "TSMC announces new fab construction timeline, infrastructure mobilization observed.",
    eventType: "economic",
    timestamp: Date.now() - 3600000 * 12,
    severity: "medium",
    source: "Tech Industry Monitor",
  },
  {
    id: "evt-4",
    lat: 22.63,
    lng: 120.31,
    title: "Kaohsiung Port Activity Surge",
    description: "Increased container vessel traffic detected at Kaohsiung, semiconductor export uptick.",
    eventType: "economic",
    timestamp: Date.now() - 3600000 * 18,
    severity: "low",
    source: "Maritime Traffic AIS",
  },
  {
    id: "evt-5",
    lat: 36.2,
    lng: 138.25,
    title: "Japan Defense Budget Discussion",
    description: "Diet proceedings on increased defense spending citing Taiwan strait stability concerns.",
    eventType: "military",
    timestamp: Date.now() - 3600000 * 24,
    severity: "medium",
    source: "Nikkei Asia Monitor",
  },
  {
    id: "evt-6",
    lat: 39.9,
    lng: 116.4,
    title: "Beijing Cross-Strait Policy Statement",
    description: "State Council releases updated position paper on Taiwan reunification framework.",
    eventType: "diplomatic",
    timestamp: Date.now() - 3600000 * 30,
    severity: "high",
    source: "Xinhua Watch",
  },
  {
    id: "evt-7",
    lat: 21.0,
    lng: 121.0,
    title: "Bashi Channel Naval Transit",
    description: "U.S. destroyer transits Bashi Channel, freedom of navigation operation confirmed.",
    eventType: "military",
    timestamp: Date.now() - 3600000 * 8,
    severity: "medium",
    source: "Pacific Fleet Monitor",
  },
  {
    id: "evt-8",
    lat: 35.0,
    lng: 105.0,
    title: "China Semiconductor Investment Fund",
    description: "New state-backed fund targets domestic chip production to reduce Taiwan supply dependence.",
    eventType: "economic",
    timestamp: Date.now() - 3600000 * 48,
    severity: "medium",
    source: "Economic Intelligence Desk",
  },
];

export function getWorldMonitorData(): WorldMonitorData {
  return {
    chokePoints: CHOKE_POINTS,
    events: GEOPOLITICAL_EVENTS,
  };
}

export const EVENT_TYPE_COLORS: Record<string, string> = {
  military: "#ef4444",
  diplomatic: "#22c55e",
  economic: "#3b82f6",
};

export const EVENT_TYPE_LABELS: Record<string, string> = {
  military: "Military / Defense",
  diplomatic: "Diplomatic",
  economic: "Economic / Infrastructure",
};
